### PR TITLE
Configurable output filename

### LINKED ISSUE #96: Make outputSpotbugsFile configurable
Hi,

Would it be possible to make outputSpotbugsFileName configurable? I've got couple of old, annoying and unmaintained tool at my company, which is required by our management to collect report from findbugs. It has hardcoded findbugs output file name as findbugsXml.xml. We would like to switch to spotbugs, but I'm not even going to force my company to force 3rd party company to fix their tooling and add support for spotbugs.

Could you consider making output report name configurable? (instead of spotbugsXml.xml). I would be happy to provide PR (adding parameter spotbugsXmlOutputFileName or outputSpotbugsFileName) for that.

Best regards,
Michal

### PR DESCRIPTION
**Pull request by cmathiesen**
Fixes #96 
This change adds an extra parameter to the configuration so you can change the file name of the spotbugsXml.xml output file

### CODE REVIEW

**Comment by hazendaz** [comment]
@cmathiesen Thanks for the work on this!  I did squash the commits to keep the history clean given the bit of trial and error there until success.

**Comment by massdosage** [comment]
Thanks @hazendaz! Could you please let us know more or less when this will be in a release that's available in Maven Central so we can start using it?

**Comment by hazendaz** [comment]
@massdosage Possibly towards end of the week.  I'm likely to list it as 3.1.12.2 to keep it in line with spotbugs main versioning.  At the moment spotbugs doesn't have any further development on 3.1.13 that is outstanding so I don't expect that anytime soon.  I've thought about moving to the 4.0.0 beta3 but there is a concerning open issue around the html site generation.  So I suspect I'll just keep running small patches against 3.1.12.x for now.

**Comment by massdosage** [comment]
OK, that sounds great, thank you!

**Comment by massdosage** [comment]
Any word on an ETA for the release?

**Comment by hazendaz** [comment]
@massdosage Most likely tomorrow evening.  I'm trying to finish up a couple things on it so that it should support jdk 8 through 14.  The work is done but the builds take a long time and I'm done for the night.  I'll let you know once it's out.  Thanks for being patient :)

**Comment by massdosage** [comment]
OK, thanks for the update. Good luck!

**Comment by hazendaz** [comment]
@massdosage The release for 3.1.12.2 has been pushed.  You should see it in central in next 2 hours.  Thanks.

**Comment by massdosage** [comment]
Thank you!

**Pull request merged**
