### PR TITLE
fix outputDirectory not work at running spotbugs:spotbugs goal

### PR DESCRIPTION
**Pull request by exiahuang**
[outputDirectory](https://spotbugs.github.io/spotbugs-maven-plugin/spotbugs-mojo.html#outputDirectory) is not working pretty well when I try to run `mvn spotbugs:spotbugs` command.
I think maybe the htmlTempFile should be use `outputDirectory`.
Can you take a look of my PR, Thank you.

### CODE REVIEW

**Comment by hazendaz** [comment]
Thanks.  Great catch.  Will get merged and a release this weekend

Sent from my Verizon, Samsung Galaxy smartphone
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
From: Exia.huangxy ***@***.***>
Sent: Wednesday, May 8, 2024 10:01:59 AM
To: spotbugs/spotbugs-maven-plugin ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [spotbugs/spotbugs-maven-plugin] fix outputDirectory not work at running spotbugs:spotbugs goal (PR #807)


outputDirectory<https://spotbugs.github.io/spotbugs-maven-plugin/spotbugs-mojo.html#outputDirectory> is not working pretty well when I try to run mvn spotbugs:spotbugs command.
I think maybe the htmlTempFile should be use outputDirectory.
Can you take a look of my PR, Thank you.

________________________________
You can view, comment on, or merge this pull request online at:

  https://github.com/spotbugs/spotbugs-maven-plugin/pull/807

Commit Summary

  *   5591f3c<https://github.com/spotbugs/spotbugs-maven-plugin/pull/807/commits/5591f3c7b49c330afa85086ce344f34725812111> fix outputDirectory not work at running spotbugs:spotbugs goal

File Changes

(1 file<https://github.com/spotbugs/spotbugs-maven-plugin/pull/807/files>)

  *   M src/main/groovy/org/codehaus/mojo/spotbugs/SpotBugsMojo.groovy<https://github.com/spotbugs/spotbugs-maven-plugin/pull/807/files#diff-a8270ec7df0fe9dcf1a1e8120b333c540187439faf5963d157f3a3e846a851e6> (2)

Patch Links:

  *   https://github.com/spotbugs/spotbugs-maven-plugin/pull/807.patch
  *   https://github.com/spotbugs/spotbugs-maven-plugin/pull/807.diff

**Comment by hazendaz** [comment]
@exiahuang Can you show what isn't working for you here?  That location is a temp file and there are others in that same spot.  project.build.directory is used in a lot of places.

**Comment by exiahuang** [comment]
@hazendaz 

If I set outputDirectory at build tag, run `mvnw spotbugs:spotbugs`, the output of html is in `target/spotbugs.html`.
not `target/test-output-directory/spotbugs.html`.

```xml
<build>
	<plugins>
		<plugin>
			<groupId>com.github.spotbugs</groupId>
			<artifactId>spotbugs-maven-plugin</artifactId>
			<!-- <version>4.8.5.1-SNAPSHOT</version> -->
			<version>4.8.5.0</version>
			<dependencies>
				<dependency>
				<groupId>com.github.spotbugs</groupId>
				<artifactId>spotbugs</artifactId>
				<version>4.8.5</version>
				</dependency>
			</dependencies>
			<configuration>
				<htmlOutput>true</htmlOutput>
				<outputDirectory>target/test-output-directory</outputDirectory>
			</configuration>
		</plugin>
	</plugins>
</build>
```

I Think [htmlTempFile](https://github.com/spotbugs/spotbugs-maven-plugin/blob/master/src/main/groovy/org/codehaus/mojo/spotbugs/SpotBugsMojo.groovy#L1101) is not just a temp file,
it is not like [xmlTempFile](https://github.com/spotbugs/spotbugs-maven-plugin/blob/master/src/main/groovy/org/codehaus/mojo/spotbugs/SpotBugsMojo.groovy#L1106) and [sarifTempFile](https://github.com/spotbugs/spotbugs-maven-plugin/blob/master/src/main/groovy/org/codehaus/mojo/spotbugs/SpotBugsMojo.groovy#L1109), 
because they will be deleted, but `htmlTempFile` is never.

**Comment by hazendaz** [comment]
ok I'll need to look more at it.  Currently this PR breaks the integration tests....

**Comment by exiahuang** [comment]
@hazendaz 
Can you Run the workflows again? I fix the test code.

**Comment by exiahuang** [comment]
@hazendaz 
There are some thing wrong with JDK23 test. I don't think it's my fault, but I don't know how to fix it.

**Comment by hazendaz** [comment]
Jdk 23 is a known and reported issue to error prone.  It only started appearing couple days ago when github updated to latest build.

Sent from my Verizon, Samsung Galaxy smartphone
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Pull request merged**
