### PR TITLE
added maxAllowedViolations property similar to checkstyle.

### PR DESCRIPTION
**Pull request by Ranjodh-Singh**
added maxAllowedViolations property similar to CheckStyle to ignore the N number of errors where N is value of the property maxAllowedViolations.
refer - #84

### CODE REVIEW

**Comment by hazendaz** [comment]
I'll look at this tonight.  There likely is a spotbugs mailing list but not on for the plugin itself.  Over on spotbugs they have this plugin documented.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by hazendaz** [comment]
Thanks @Ranjodh-Singh. this is now merged.  I'm waiting on groovy support for jdk11 before next release.  If you need this out sooner, I can look at releasing a patch next weekend.  Let me know...

**Comment by hazendaz** [comment]
@Ranjodh-Singh If you can, please write a unit test in the integration tests to test this feature.

**Comment by Ranjodh-Singh** [comment]
thanks @hazendaz  I will be updating the unit test case for this one.

**Comment by Ravik5** [comment]
Is anyone used in a Gradle project, If yes can you guide me??

**Comment by hazendaz** [comment]
@Ravik5 you would want to confirm that is coded which it should be in the gradle plugin as this one is maven -> https://github.com/spotbugs/spotbugs-gradle-plugin

**Comment by Ravik5** [comment]
No , I have not added any code, Let me know if there is something in Gradle I can use??

**Pull request merged**
