### PR TITLE
Make sarifOutputDirectory and sarifOutputFilename configurable

### LINKED ISSUE #506: Make sarifFinalFile folder customisable
Currently defaults to `${project.build.directory}` but should be configurable, just as the [`<xmlOutputDirectory>`](https://spotbugs.github.io/spotbugs-maven-plugin/spotbugs-mojo.html#xmlOutputDirectory) and [`<spotbugsXmlOutputDirectory>`](https://spotbugs.github.io/spotbugs-maven-plugin/spotbugs-mojo.html#spotbugsXmlOutputDirectory) parameters allow.

### LINKED ISSUE #507: Make sarif output file name customisable
The plugin currently uses `spotbugsSarif.json` as output for SARIF files. Some plugins however rely on the `.sarif` file extension (i.e. [`github/codeql-action/upload-sarif`](https://github.com/github/codeql-action/blob/main/src/upload-lib.ts#L153). The current parameters do not allow to set a custom SARIF output file name/extension.

### PR DESCRIPTION
**Pull request by jwgmeligmeyling**
Fixes #506 
Fixes #507

### CODE REVIEW

**Comment by hazendaz** [comment]
@jwgmeligmeyling The force file happens earlier, is it needed to happen there as well?  Seems like its happening twice with this change.

**Comment by jwgmeligmeyling** [comment]
The other forceFile only happens on the temporary file location, not the resultFile. The resultFile relied on the forceFile(temporaryResult) to create the parent folders, but with this change these folders may now differ. I actually amended it to my copy later when I noticed it wasn't working.

**Comment by hazendaz** [comment]
Totally missed that key difference.  Thanks.  Will get this merged in and a release sometime this weekend.

Sent from my Verizon, Samsung Galaxy smartphone
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by hazendaz** [comment]
@jwgmeligmeyling This has been released as 4.7.2.2 now.

**Comment by jwgmeligmeyling** [comment]
Thanks! 👍🏻

**Pull request merged**
