### PR TITLE
CheckMojo: introduce failThreshold

### LINKED ISSUE #219: check goal: introduce failThreshold or similar
As of 4.0.0 I cannot collect _all_ bugs (`<threshold>Low</threshold>`) but only fail if there are "Normal" or "High" bugs.

If there was a `failThreshold` parameter I could say:
```xml
<threshold>Low</threshold>
<failThreshold>Normal</failThreshold>
```
and the report should then contain _all_ bugs but would not _fail_ if there were only "Low" bugs.

Bonus: Log all bugs that are below the `failThreshold` as a warning.

### PR DESCRIPTION
**Pull request by famod**
Resolves #219

Notes:
- First I cleaned up the duplicate parsing of `outputFile` and the scoping of `bugCount` and `errorCount` (see first commit)
- The recent Groovy update from 3.0.3 to 3.0.4 kills your builds: https://travis-ci.org/github/spotbugs/spotbugs-maven-plugin/builds/690024559
  ```
  [ERROR] Failed to execute goal org.apache.maven.plugins:maven-invoker-plugin:3.2.1:install (prepare-integration-test) on project spotbugs-maven-plugin: Execution prepare-integration-test of goal org.apache.maven.plugins:maven-invoker-plugin:3.2.1:install failed: Plugin org.apache.maven.plugins:maven-invoker-plugin:3.2.1 or one of its dependencies could not be resolved: Could not find artifact org.testng:testng:jar:7.2.0 in google-maven-central (https://maven-central.storage-download.googleapis.com/maven2/) -> [Help 1]
  ```
  I get the same error locally ~which is why this change is not in my PR branch (based on https://github.com/spotbugs/spotbugs-maven-plugin/commit/689c796ac24009e2f79a01fc7f48f608cf13ae67 instead).~ (see first comment)
- This PR also adds a priority prefix to the log message:
  Before:
  ```
  [ERROR] Overwritten increment in UselessAssignments.oops() [UselessAssignments] At UselessAssignments.java:[line 30] DLS_OVERWRITTEN_INCREMENT
  ```
  With this PR:
  ```
  [ERROR] High: Overwritten increment in UselessAssignments.oops() [UselessAssignments] At UselessAssignments.java:[line 30] DLS_OVERWRITTEN_INCREMENT
  ```

### CODE REVIEW

**Comment by famod** [comment]
I just realized that your Travis build uses the latest commits anyway so I rebased my branch.
This will (of cource) fail all the builds for this PR until the TestNG problem is fixed.

**Comment by famod** [comment]
@hazendaz WDYT?

**Comment by hazendaz** [comment]
travis ci is dicey these days.  I tried to rebuild this yesterday but no luck.  Issue was not groovy but rather the invoker pulling testng.  I don't see us using testng but it's having issues getting it.  I tried running it again tonight.  I'd like to see travis successful.  I also need to wrap my head around the changes a bit more.  A quick look seems ok but just want to review some of the naming changes and make sure it looks appropriate for current usage.  So I'm on board with it just need to get travis working and look at it in a little more depth.  I'll try to get to it in next couple of days.  If travis continues to fail, can you take a look at what might be causing that?  I'm pretty sure when I upgraded groovy it was fine on that pull request.  I usually skip merging if travis is having issues unless its related to pulling a lib it cannot find.  That could have been the case on the groovy update.  I don't recall off hand.

**Comment by famod** [comment]
@hazendaz

Well, the Groovy upgrade PR ran into the same problem: https://github.com/spotbugs/spotbugs-maven-plugin/pull/221
I can reproduce it locally, so this is not a Travis problem, AFAICS.

**Comment by hazendaz** [comment]
@famod Thanks.  I'll take a look tonight.

**Comment by famod** [comment]
@hazendaz friendly reminder! 🙂

**Comment by hazendaz** [comment]
I need to ping testng folks I think to get them to release their binary.  Their github states it was released but obviously wans't in central last I checked.  I kicked off another build just now.  If it fails again, I'll reach out to that team.

**Comment by famod** [comment]
So it failed again.

IMHO, the groovy update should be rolled back for now.

**Comment by hazendaz** [comment]
@famod Rebuilding now.  Issue fixed.  We don't use testng but the groovy plugin uses groovy all which we override to latest.  Per groovy, they messed up by using testng on version not released to central, testng has since removed notice of testng release.  Since we don't use testng, I followed groovy's work around to exclude it from the groovy plugin and builds are back to normal.  As soon as this goes green, I'll review once again and then get it merged.

**Comment by hazendaz** [comment]
@famod Thank you! Merging now.

**Comment by hazendaz** [comment]
@famod I'm waiting on a pull request to be corrected so the test for htm vs xml works.  I'd like to include that.  So hopefully soon.  If I don't hear anything back this coming week on the other pull request, I'll likely just move fowards without it.

**Comment by famod** [comment]
Thanks for your feedback!

**Comment by famod** [comment]
@hazendaz Any news regarding a new release? Thanks!

**Comment by hazendaz** [comment]
@famod I'll release this tonight.

**Comment by hazendaz** [comment]
@famod Released, it will be available in central in next 2 hours or so.  You should be able to otherwise pull it probably in about 15 minutes or so.

**Comment by hazendaz** [comment]
Version 4.0.4 to match line of spotbugs.

**Comment by famod** [comment]
@hazendaz Great, thanks!

**Pull request merged**
